# 1. Site Branding
title: "0xuncl3_n3rd's Blog"     # Appears in the sidebar and browser tab
tagline: "CTF Player,Vulnerability Researcher " # Subtitle under your name
description: "Writeups for HackTheBox, TryHackMe, major CTF events and more Tech stuff."

# 2. Production URL Configuration
url: "https://0xuncl3-n37d-github-io.vercel.app"  # Change to your actual domain or GitHub Pages link
baseurl: ""                            # Keep empty if your site is at the root of the domain

# 3. Personalization & Localization
timezone: Africa/Nairobi               # Set your local timezone
lang: en                               # Preferred language

# 4. Avatar & Profile Configuration
avatar: "/assets/img/avatar_profile.png"       # Path to your profile picture inside your repo

# 5. Theme Configurations
theme_mode: dark                       # Options: 'light', 'dark', or 'prefer-system'
toc: true                              # Enables Table of Contents on the side of writeups

social:
  name: "Uncle_N3rd"
  email: "isaackash254@gmail.com"
  github: "Lupah-T"                # Only the username, NO full URL string
  twitter: "KidLupah5478"          # Only the handle, NO full URL string
